version: '3'

services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./src:/app/src
    ports:
      - "3000:3000"
    command:
      - npm
      - run
      - dev

  postgresql:
    image: "postgres:latest"
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@admin
      POSTGRES_DB: gados
    ports:
      - '5432:5432'