version: '3'

services:
  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - postgresql

  postgresql:
    image: "postgres:latest"
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@admin
      POSTGRES_DB: gados
    ports:
      - '5432:5432'